---

- name: Create kubernetes configuration directory
  file:
    path: "{{ item }}"
    mode: '0755'
    state: directory
  with_items:
    - /etc/kubernetes/config
    - /var/lib/kubernetes

- name: Download and Install kubernetes controller binaries
  get_url:
    url: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: '0755'
  with_items:
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-apiserver
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-controller-manager
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kube-scheduler
    - https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/amd64/kubectl
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"


- name: Copy certificates
  copy:
    src: /root/{{ item }}
    dest: /var/lib/kubernetes/{{ item }}
    remote_src: yes
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes.pem
    - kubernetes-key.pem
    - service-account.pem
    - service-account-key.pem
    - encryption-config.yaml


- name: Distribute Configurations
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

# Configure Kubernetes Controller Manager #
- name: Distribute Controller Config
  copy:
    src: /root/kube-controller-manager.kubeconfig
    dest: /etc/systemd/system/kube-controller-manager.kubeconfig
    remote_src: yes

- name: Distribute Kube Controller Manager
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

# Configure Kubernetes Scheduler #
- name: kube-scheduler.kubeconfig
  copy:
    src: /root/kube-scheduler.kubeconfig
    dest: /var/lib/kubernetes/kube-scheduler.kubeconfig
    remote_src: yes

- name: kubernetes scheduler
  template:
    src: kube-scheduler.yaml.j2
    dest: /etc/kubernetes/config/kube-scheduler.yaml

- name: Kubernetes scheduler service
  template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service


# reload
- name: reload systemd
  systemd:
    daemon_reload: yes


# install nginx
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Nginx Configurations
  template:
    src: kubernetes.default.svc.cluster.local.j2
    dest: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local

- name: make a symlink
  file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    state: link


